branches:
  only:
    - master

version: 0.1.{build}-ci
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

os: Visual Studio 2015
install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

before_build:
  nuget restore "Sancho.XAMLParser.AppVeyor.sln"

configuration: Release
platform: Any CPU

build:
  parallel: true
  project: src/Sancho.XAMLParser/Sancho.XAMLParser.csproj
  verbosity: minimal

test:
  assemblies:
    - '**\*.tests.dll'
      
after_build:
  - ps: msbuild "src/Sancho.XAMLParser/Sancho.XAMLParser.csproj" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: nuget pack src/Sancho.XAMLParser/Sancho.XAMLParser.csproj -Version $env:APPVEYOR_BUILD_VERSION
artifacts:
  - path: '**\Sancho.*.nupkg'
